name: CI • tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # dev-зависимости для тестов:
          echo "pytest
httpx
anyio
" > requirements-dev.txt
          pip install -r requirements-dev.txt

      - name: Run pytest
        env:
          # чтобы fastapi TestClient видел переменные окружения
          ENV: test
          MODE: web
          LOG_LEVEL: WARNING
        run: |
          python -c "import sys; print(sys.version)"
          pytest -q
