name: Daily pulse content

on:
  schedule:
    - cron: "59 18 * * *"   # 21:59 MSK (UTC+3)
  workflow_dispatch:

jobs:
  pulse:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Make pulse entry
        id: make
        run: |
          python -m pip install --upgrade pip
          python tools/make_pulse_entry.py
        shell: bash

      - name: Push changes
        if: always()
        run: |
          git config user.name "elaya-bot"
          git config user.email "actions@github.com"
          git push
        shell: bash

      - name: Send to Telegram
        env:
          TG_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT:  ${{ secrets.TG_STATUS_CHAT_ID }}
        run: |
          set -e
          msg="$(echo '${{ steps.make.outputs.pulse_json }}' | python - << 'PY'
import sys, json
print(json.load(sys.stdin)["text"])
PY
)"
          curl -sS -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
            -d "chat_id=${TG_CHAT}" \
            --data-urlencode "text=${msg}" \
            -d "parse_mode=HTML" >/dev/null
