name: Daily pulse content

on:
  schedule:
    - cron: "59 18 * * *"   # 21:59 MSK (UTC+3)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pulse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate pulse
            env:
      # PULSE-секреты (основные)
      PULSE_TG_TOKEN: ${{ secrets.PULSE_TG_TOKEN }}
      PULSE_TG_CHAT_ID: ${{ secrets.PULSE_TG_CHAT_ID }}
      # Fallback на уже существующие HQ-бота (если PULSE_* не заданы)
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_STATUS_CHAT_ID: ${{ secrets.TG_STATUS_CHAT_ID }}


      - name: Commit changes
        run: |
          git config user.name "elaya-bot"
          git config user.email "elaya-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore(pulse): add daily pulse and update README"
            git push
          fi
