name: Daily pulse content

on:
  workflow_dispatch:
  schedule:
    - cron: '59 18 * * *'  # 21:59 MSK (UTC+3)

permissions:
  contents: write

jobs:
  pulse:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout (develop)
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip

      - name: Generate pulse
        run: |
          python tools/make_pulse_entry.py

      - name: Commit & push
        run: |
          git config user.name  "elaya-bot"
          git config user.email "elaya-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore(pulse): add daily pulse and update README"
            git push
          fi
name: Daily pulse content

on:
  workflow_dispatch:
  schedule:
    - cron: '59 18 * * *'  # 21:59 MSK (UTC+3)

permissions:
  contents: write

jobs:
  pulse:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout (develop)
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip

      - name: Generate pulse
        run: |
          python tools/make_pulse_entry.py

      - name: Commit & push
        run: |
          git config user.name  "elaya-bot"
          git config user.email "elaya-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore(pulse): add daily pulse and update README"
            git push
          fi
