name: Daily Pulse Content

on:
  schedule:
    - cron: "59 18 * * *"  # 21:59 MSK (UTC+3)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  make-pulse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip

      - name: Generate Elaya Pulse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_STATUS_CHAT_ID: ${{ secrets.TG_STATUS_CHAT_ID }}
        run: |
          python tools/make_pulse_entry.py

      - name: Push changes (fallback)
        if: ${{ always() }}
        run: |
          git config user.name "elaya-bot"
          git config user.email "bot@users.noreply.github.com"
          git add docs/pulse README.md || true
          git commit -m "chore(pulse): auto-update latest pulse" || echo "nothing to commit"
          git push
