name: Deploy to Staging (Render)

on:
  push:
    branches: [ "develop" ]
    paths:
      - "app/**"
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/deploy-staging.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/elaya-stagecoach
      TAG: develop

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Wait for tag propagation
        run: sleep 10

      - name: Trigger Render WEB deploy (optional)
        if: ${{ secrets.RENDER_DEPLOY_HOOK_WEB != '' }}
        env:
          HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_WEB }}
        run: |
          echo "Trigger WEB hook: $HOOK"
          curl -fsS -X POST "$HOOK"

      - name: Trigger Render BOT deploy (optional)
        if: ${{ secrets.RENDER_DEPLOY_HOOK_BOT != '' }}
        env:
          HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_BOT }}
        run: |
          echo "Trigger BOT hook: $HOOK"
          curl -fsS -X POST "$HOOK"
