name: Deploy staging

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Render (WEB)
        if: ${{ env.RENDER_DEPLOY_HOOK_WEB != '' }}
        env:
          RENDER_DEPLOY_HOOK_WEB: ${{ secrets.RENDER_DEPLOY_HOOK_WEB }}
        run: |
          echo "Deploying WEB service..."
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK_WEB"

      - name: Deploy to Render (BOT)
        if: ${{ env.RENDER_DEPLOY_HOOK_BOT != '' }}
        env:
          RENDER_DEPLOY_HOOK_BOT: ${{ secrets.RENDER_DEPLOY_HOOK_BOT }}
        run: |
          echo "Deploying BOT service..."
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK_BOT"
