name: Repo Audit

on:
  workflow_dispatch:   # запуск вручную из вкладки Actions

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # ставим зависимости, если они есть

      - name: Run repo_audit.py
        run: python repo_audit.py
